import { BASE_SAMPLE_DATA } from "../sample-data";
import type { EmailTemplate } from "../types";

function tpl(
  partial: Omit<EmailTemplate, "sampleData"> & { extraSample?: Record<string, string> },
): EmailTemplate {
  return { showTrustBadges: true, ...partial, sampleData: { ...BASE_SAMPLE_DATA, ...partial.extraSample } };
}

const p = (text: string) => `<p style="margin:0 0 16px;">${text}</p>`;

export const MARKETING_EMAIL_TEMPLATES: EmailTemplate[] = [
  tpl({
    id: "new-product",
    name: "New Product",
    category: "marketing",
    subject: "Introducing {{product_name}} — New from BeyondBabyCo",
    preheader: "Research-backed baby care, now available.",
    heading: "New Product Launch",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("We're excited to introduce <strong>{{product_name}}</strong> — developed with the same research-first approach you trust.")}${p("Dermatologically tested. Made in India. Created with love.")}`,
    cta: { label: "Shop Now", href: "{{product_url}}" },
  }),
  tpl({
    id: "launch-campaign",
    name: "Launch Campaign",
    category: "marketing",
    subject: "{{campaign_name}} — BeyondBabyCo is here!",
    preheader: "The wait is over. Discover research-backed baby care.",
    heading: "{{campaign_name}}",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("BeyondBabyCo is officially launching — bringing five years of research to gentle baby care products families can trust.")}${p("Be among the first to experience the difference.")}`,
    cta: { label: "Explore Collection", href: "{{site_url}}/products" },
    secondaryCta: { label: "Trust Center", href: "{{site_url}}/trust-center" },
  }),
  tpl({
    id: "festival-campaign",
    name: "Festival Campaign",
    category: "marketing",
    subject: "🎉 {{campaign_name}} — Special offers inside",
    preheader: "Celebrate with gentle care for your little one.",
    heading: "{{campaign_name}}",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("This festive season, give your baby the gentlest touch with BeyondBabyCo's research-backed essentials.")}${p("Enjoy special festival offers on selected products — valid until {{offer_expiry}}.")}`,
    cta: { label: "Shop Festival Offers", href: "{{site_url}}/products" },
  }),
  tpl({
    id: "offers",
    name: "Offers",
    category: "marketing",
    subject: "Special offer for you, {{customer_name}}",
    preheader: "Exclusive savings on BeyondBabyCo products.",
    heading: "A Special Offer Just For You",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("We have an exclusive offer waiting for you — {{coupon_discount}} on your next order.")}${p("Valid until {{offer_expiry}}.")}`,
    cta: { label: "Shop Now", href: "{{site_url}}/products" },
  }),
  tpl({
    id: "coupons",
    name: "Coupons",
    category: "marketing",
    subject: "Your coupon code: {{coupon_code}}",
    preheader: "Use {{coupon_code}} for {{coupon_discount}}.",
    heading: "Your Exclusive Coupon",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Use code <strong style=\"font-size:20px;color:#cd6a45;\">{{coupon_code}}</strong> at checkout for {{coupon_discount}}.")}${p("Expires {{offer_expiry}}.")}`,
    cta: { label: "Apply Coupon", href: "{{site_url}}/products" },
  }),
  tpl({
    id: "wishlist-reminder",
    name: "Wishlist Reminder",
    category: "marketing",
    subject: "Items in your wishlist are waiting",
    preheader: "Don't forget the products you saved.",
    heading: "Your Wishlist Misses You",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("You have items saved in your wishlist, including <strong>{{product_name}}</strong>.")}${p("Research-backed baby care — ready when you are.")}`,
    cta: { label: "View Wishlist", href: "{{wishlist_url}}" },
  }),
  tpl({
    id: "cart-reminder",
    name: "Cart Reminder",
    category: "marketing",
    subject: "You left something behind",
    preheader: "Complete your BeyondBabyCo order.",
    heading: "Complete Your Order",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("You have items waiting in your cart. Gentle, research-backed baby care is just a click away.")}${p("Your cart total: <strong>{{order_total}}</strong>")}`,
    cta: { label: "Complete Checkout", href: "{{cart_url}}" },
  }),
  tpl({
    id: "back-in-stock",
    name: "Back in Stock",
    category: "marketing",
    subject: "{{product_name}} is back in stock!",
    preheader: "Good news — your saved item is available again.",
    heading: "Back In Stock",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("<strong>{{product_name}}</strong> is back in stock and ready to order.")}${p("Stock is limited — order soon to avoid missing out.")}`,
    cta: { label: "Shop Now", href: "{{product_url}}" },
  }),
  tpl({
    id: "birthday",
    name: "Birthday",
    category: "marketing",
    subject: "Happy Birthday, {{customer_name}}! 🎂",
    preheader: "A birthday gift from BeyondBabyCo — {{birthday_offer}}.",
    heading: "Happy Birthday!",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Wishing you and your little one a wonderful birthday!")}${p("As a gift, enjoy <strong>{{birthday_offer}}</strong> — our way of saying thank you for being part of the BeyondBabyCo family.")}`,
    cta: { label: "Claim Birthday Offer", href: "{{site_url}}/products" },
  }),
  tpl({
    id: "newsletter",
    name: "Newsletter",
    category: "marketing",
    subject: "BeyondBabyCo Newsletter — Research, Tips & New Arrivals",
    preheader: "Latest from BeyondBabyCo — gentle care insights for parents.",
    heading: "BeyondBabyCo Newsletter",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Welcome to the BeyondBabyCo family newsletter. Each edition brings research insights, parenting tips, and first access to new products.")}${p("Research-backed. Parent-approved. Made with love in India.")}`,
    cta: { label: "Read Latest Research", href: "{{research_url}}" },
    secondaryCta: { label: "Shop Products", href: "{{site_url}}/products" },
  }),
  tpl({
    id: "research-stories",
    name: "Research Stories",
    category: "marketing",
    subject: "{{research_title}}",
    preheader: "Discover the science behind BeyondBabyCo.",
    heading: "{{research_title}}",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Every BeyondBabyCo product begins with research. In this edition, we share how five years of ingredient science became products your family can trust.")}${p("From lab to label — transparency you can see.")}`,
    cta: { label: "Explore Research", href: "{{research_url}}" },
    secondaryCta: { label: "Trust Center", href: "{{site_url}}/trust-center" },
  }),
];
