import { BASE_SAMPLE_DATA } from "../sample-data";
import type { EmailTemplate } from "../types";

function tpl(
  partial: Omit<EmailTemplate, "sampleData"> & { extraSample?: Record<string, string> },
): EmailTemplate {
  return { showTrustBadges: true, ...partial, sampleData: { ...BASE_SAMPLE_DATA, ...partial.extraSample } };
}

const p = (text: string) => `<p style="margin:0 0 16px;">${text}</p>`;
const orderSummary = `${p("<strong>Order:</strong> {{order_number}}")}${p("<strong>Date:</strong> {{order_date}}")}${p("<strong>Total:</strong> {{order_total}}")}`;

export const ORDER_EMAIL_TEMPLATES: EmailTemplate[] = [
  tpl({
    id: "order-confirmation",
    name: "Order Confirmation",
    category: "order",
    subject: "Order confirmed — {{order_number}}",
    preheader: "Thank you for your order! We're preparing it with care.",
    heading: "Order Confirmed",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Thank you for shopping with BeyondBabyCo. Your order has been confirmed and is being prepared.")}${orderSummary}${p("<strong>Delivery to:</strong><br/>{{delivery_address}}")}`,
    cta: { label: "View Order", href: "{{order_url}}" },
  }),
  tpl({
    id: "payment-received",
    name: "Payment Received",
    category: "order",
    subject: "Payment received for order {{order_number}}",
    preheader: "We've received your payment of {{order_total}}.",
    heading: "Payment Received",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("We've successfully received your payment of <strong>{{order_total}}</strong> via {{payment_method}} for order {{order_number}}.")}${orderSummary}`,
    cta: { label: "View Order", href: "{{order_url}}" },
  }),
  tpl({
    id: "payment-failed",
    name: "Payment Failed",
    category: "order",
    subject: "Payment failed for order {{order_number}}",
    preheader: "Your payment could not be processed.",
    heading: "Payment Could Not Be Processed",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Unfortunately, your payment for order {{order_number}} could not be processed. Please try again or choose a different payment method.")}${p("Your items are reserved for a limited time.")}`,
    cta: { label: "Retry Payment", href: "{{order_url}}" },
    secondaryCta: { label: "Contact Support", href: "{{support_url}}" },
  }),
  tpl({
    id: "cod-confirmation",
    name: "COD Confirmation",
    category: "order",
    subject: "COD order confirmed — {{order_number}}",
    preheader: "Your Cash on Delivery order is confirmed.",
    heading: "Cash on Delivery Order Confirmed",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Your Cash on Delivery order {{order_number}} has been confirmed. Please keep <strong>{{order_total}}</strong> ready at the time of delivery.")}${orderSummary}`,
    cta: { label: "Track Order", href: "{{order_url}}" },
  }),
  tpl({
    id: "invoice",
    name: "Invoice",
    category: "order",
    subject: "Invoice for order {{order_number}}",
    preheader: "Your invoice is ready to download.",
    heading: "Your Invoice",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Your invoice for order {{order_number}} ({{order_total}}) is ready.")}${orderSummary}`,
    cta: { label: "Download Invoice", href: "{{invoice_url}}" },
  }),
  tpl({
    id: "order-packed",
    name: "Order Packed",
    category: "order",
    subject: "Your order {{order_number}} has been packed",
    preheader: "Great news — your order is packed and ready to ship.",
    heading: "Order Packed",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Your BeyondBabyCo order {{order_number}} has been carefully packed and is ready for dispatch.")}${p("You'll receive tracking details once your shipment is created.")}`,
    cta: { label: "View Order", href: "{{order_url}}" },
  }),
  tpl({
    id: "shipment-created",
    name: "Shipment Created",
    category: "order",
    subject: "Your order {{order_number}} has shipped",
    preheader: "Track your shipment — {{tracking_number}}",
    heading: "Shipment Created",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Your order {{order_number}} has been dispatched via {{carrier_name}}.")}${p("<strong>Tracking number:</strong> {{tracking_number}}")}${p("<strong>Estimated delivery:</strong> {{estimated_delivery}}")}`,
    cta: { label: "Track Shipment", href: "{{order_url}}" },
  }),
  tpl({
    id: "order-out-for-delivery",
    name: "Out For Delivery",
    category: "order",
    subject: "Out for delivery — order {{order_number}}",
    preheader: "Your BeyondBabyCo order arrives today!",
    heading: "Out For Delivery",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Great news! Your order {{order_number}} is out for delivery and should arrive today.")}${p("Please ensure someone is available to receive the package.")}`,
    cta: { label: "Track Delivery", href: "{{order_url}}" },
  }),
  tpl({
    id: "order-delivered",
    name: "Delivered",
    category: "order",
    subject: "Delivered — order {{order_number}}",
    preheader: "Your BeyondBabyCo order has been delivered.",
    heading: "Order Delivered",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Your order {{order_number}} has been delivered. We hope your little one loves their new BeyondBabyCo products!")}${p("If anything isn't right, our support team is here to help.")}`,
    cta: { label: "View Order", href: "{{order_url}}" },
    secondaryCta: { label: "Leave a Review", href: "{{site_url}}/products" },
  }),
  tpl({
    id: "order-cancelled",
    name: "Cancelled",
    category: "order",
    subject: "Order {{order_number}} cancelled",
    preheader: "Your order has been cancelled.",
    heading: "Order Cancelled",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Your order {{order_number}} has been cancelled as requested.")}${p("If a payment was made, your refund will be processed within 5–7 business days.")}`,
    cta: { label: "Shop Again", href: "{{site_url}}/products" },
    secondaryCta: { label: "Contact Support", href: "{{support_url}}" },
  }),
  tpl({
    id: "refund-initiated",
    name: "Refund Initiated",
    category: "order",
    subject: "Refund initiated for order {{order_number}}",
    preheader: "We're processing your refund of {{refund_amount}}.",
    heading: "Refund Initiated",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("We've initiated a refund of <strong>{{refund_amount}}</strong> for order {{order_number}}.")}${p("Refunds typically appear in your account within 5–7 business days, depending on your bank.")}`,
    cta: { label: "View Order", href: "{{order_url}}" },
  }),
  tpl({
    id: "refund-completed",
    name: "Refund Completed",
    category: "order",
    subject: "Refund completed — {{refund_amount}}",
    preheader: "Your refund has been processed successfully.",
    heading: "Refund Completed",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Your refund of <strong>{{refund_amount}}</strong> for order {{order_number}} has been completed on {{refund_date}}.")}${p("Please allow 3–5 additional business days for the amount to reflect in your account.")}`,
    cta: { label: "Shop Again", href: "{{site_url}}/products" },
  }),
  tpl({
    id: "return-requested",
    name: "Return Requested",
    category: "order",
    subject: "Return request received — order {{order_number}}",
    preheader: "We've received your return request.",
    heading: "Return Request Received",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("We've received your return request for order {{order_number}}.")}${p("<strong>Reason:</strong> {{return_reason}}")}${p("Our team will review your request and respond within one business day.")}`,
    cta: { label: "View Return Status", href: "{{order_url}}" },
  }),
  tpl({
    id: "return-approved",
    name: "Return Approved",
    category: "order",
    subject: "Return approved — order {{order_number}}",
    preheader: "Your return request has been approved.",
    heading: "Return Approved",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Your return request for order {{order_number}} has been approved.")}${p("Please follow the return instructions sent separately. Once we receive the item, your refund will be processed.")}`,
    cta: { label: "Return Policy", href: "{{site_url}}/return-policy" },
  }),
  tpl({
    id: "return-completed",
    name: "Return Completed",
    category: "order",
    subject: "Return completed — order {{order_number}}",
    preheader: "Your return has been processed.",
    heading: "Return Completed",
    bodyHtml: `${p("Hi {{customer_name}},")}${p("Your return for order {{order_number}} has been completed. Refund of {{refund_amount}} will be processed shortly.")}`,
    cta: { label: "View Order", href: "{{order_url}}" },
  }),
];
