import {
  Award,
  BadgeCheck,
  Beaker,
  Box,
  ClipboardCheck,
  ClipboardList,
  Droplets,
  Factory,
  FlaskConical,
  Headphones,
  HeartPulse,
  Home,
  Leaf,
  Lock,
  MessageCircle,
  Minimize2,
  Package,
  PackageCheck,
  Recycle,
  RotateCcw,
  SearchCheck,
  Shield,
  ShieldCheck,
  Stethoscope,
  Truck,
  Users,
  Warehouse,
  type LucideIcon,
} from "lucide-react";

export const TRUST_ICON_MAP: Record<string, LucideIcon> = {
  beaker: Beaker,
  leaf: Leaf,
  flask: FlaskConical,
  shield: Shield,
  "shield-check": ShieldCheck,
  stethoscope: Stethoscope,
  "heart-pulse": HeartPulse,
  "clipboard-check": ClipboardCheck,
  factory: Factory,
  "badge-check": BadgeCheck,
  "message-circle": MessageCircle,
  package: Package,
  "search-check": SearchCheck,
  box: Box,
  warehouse: Warehouse,
  truck: Truck,
  home: Home,
  recycle: Recycle,
  "minimize-2": Minimize2,
  "package-check": PackageCheck,
  award: Award,
  lock: Lock,
  "rotate-ccw": RotateCcw,
  headphones: Headphones,
  users: Users,
  "flask-conical": FlaskConical,
  "clipboard-list": ClipboardList,
  droplets: Droplets,
};

export function TrustIcon({ name, className }: { name: string; className?: string }) {
  const Icon = TRUST_ICON_MAP[name];
  if (!Icon) return null;
  return <Icon className={className} aria-hidden="true" strokeWidth={1.75} />;
}
